# devops/Dockerfile.backend
FROM eclipse-temurin:17-jdk

WORKDIR /app

# Copier le JAR
COPY ../backend/target/*.jar app.jar

EXPOSE 8080

ENV SPRING_PROFILES_ACTIVE=prod

ENTRYPOINT ["java","-jar","app.jar"]
