# Dockerfile.frontend
FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# On nettoie le contenu par défaut de Nginx
RUN rm -rf ./*

# ⬅️ IMPORTANT :
# - le contexte de build est la racine du projet (betteryou/)
# - le build Vite est dans frontend/dist
COPY frontend/dist .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
