package ma.betteryou.betteryoubackend.service.ai.nutrition;

import lombok.RequiredArgsConstructor;
import ma.betteryou.betteryoubackend.dto.Nutrition.AiNutritionGenerateRequest;
import ma.betteryou.betteryoubackend.dto.Nutrition.AiNutritionGenerateResponse;
import ma.betteryou.betteryoubackend.dto.Nutrition.NutritionPlanDto;
import ma.betteryou.betteryoubackend.entity.nutrition.NutritionPlan;
import ma.betteryou.betteryoubackend.entity.user.User;
import ma.betteryou.betteryoubackend.repository.NutritionPlanRepository;
import ma.betteryou.betteryoubackend.repository.UserRepository;

import java.time.LocalDate;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ma.betteryou.betteryoubackend.service.NutritionService.NutritionPlanService;

@Service
@RequiredArgsConstructor
public class AiNutritionGenerateServiceImpl implements AiNutritionGenerateService {

    private final OpenAiNutritionClient openAiNutritionClient;
    private final UserRepository userRepository;
    private final NutritionPlanRepository nutritionPlanRepository;
    private final NutritionPlanService nutritionPlanService;


    @Value("${ai.openai.model:gpt-4o-mini}")
    private String aiModel;

    @Override
    public AiNutritionGenerateResponse generate(AiNutritionGenerateRequest req) {

        if (req == null) throw new RuntimeException("Request body is required");
        if (req.getUserId() == null) throw new RuntimeException("userId is required");
        if (req.getStartDate() == null || req.getEndDate() == null)
            throw new RuntimeException("startDate and endDate are required");
        if (req.getCaloriesPerDay() == null || req.getCaloriesPerDay() <= 0)
            throw new RuntimeException("caloriesPerDay must be > 0");

        User user = userRepository.findById(req.getUserId())
                .orElseThrow(() -> new RuntimeException("User not found: " + req.getUserId()));

        // ✅ Prompt بسيط الآن: فقط الاسم + وصف
        String prompt = """
        Return ONLY JSON:
        {
          "nutritionName": "string",
          "description": "string"
        }
        Objective: %s
        Calories per day: %s
        Start: %s
        End: %s
        User: gender=%s height_cm=%s initial_weight_kg=%s activity_level=%s fitness_level=%s food_preferences=%s
        """.formatted(
                safe(req.getObjective()),
                req.getCaloriesPerDay(),
                req.getStartDate(),
                req.getEndDate(),
                safe(user.getGender() != null ? user.getGender().name() : null),
                user.getHeightCm(),
                user.getInitialWeightKg(),
                safe(user.getActivityLevel() != null ? user.getActivityLevel().name() : null),
                safe(user.getFitnessLevel() != null ? user.getFitnessLevel().name() : null),
                safe(user.getFoodPreferences() != null ? user.getFoodPreferences().name() : null)
        );

        String aiJson = openAiNutritionClient.generateJson(prompt);

        // ✅ استخراج بسيط من JSON (بدون Parser كبير الآن)
        String name = extractField(aiJson, "nutritionName", "AI Nutrition Plan");
        String desc = extractField(aiJson, "description", "Generated by AI");

        NutritionPlanDto savedDto = savePlan(req, user, name, desc);

      return AiNutritionGenerateResponse.builder()
        .nutritionPlanId(savedDto.getIdNutrition())
        .nutritionName(savedDto.getNutritionName())
        .objective(savedDto.getObjective())
        .caloriesPerDay(savedDto.getCaloriesPerDay())
        .startDate(LocalDate.parse(savedDto.getStartDate()))
        .endDate(LocalDate.parse(savedDto.getEndDate()))
        .generated(true)
        .aiModel(aiModel)
        .build();


    }

    @Transactional
    protected NutritionPlanDto savePlan(AiNutritionGenerateRequest req, User user, String name, String desc) {

       NutritionPlanDto dto = NutritionPlanDto.builder()
        .nutritionName(name)
        .description(desc)
        .objective(req.getObjective())
        .caloriesPerDay(req.getCaloriesPerDay())
        .startDate(req.getStartDate().toString())
        .idUser(user.getIdUser())
        .build();

return nutritionPlanService.saveNutritionPlanDto(dto);


    }

    private String safe(String v) {
        return v == null ? "UNKNOWN" : v;
    }

    /**
     * Extract naive JSON field without adding new parser files now.
     * Works for simple testing only.
     */
    private String extractField(String json, String field, String fallback) {
        try {
            String key = "\"" + field + "\"";
            int k = json.indexOf(key);
            if (k < 0) return fallback;
            int colon = json.indexOf(":", k);
            int firstQuote = json.indexOf("\"", colon + 1);
            int secondQuote = json.indexOf("\"", firstQuote + 1);
            if (firstQuote < 0 || secondQuote < 0) return fallback;
            return json.substring(firstQuote + 1, secondQuote).trim();
        } catch (Exception e) {
            return fallback;
        }
    }
}
